spring:
    gateway:
#      httpclient:
#        ssl:
#          handshake-timeout-millis: 10000
#          close-notify-flush-timeout-millis: 3000
#          close-notify-read-timeout-millis: 0
#      routes:
      # - id: ui_path_route
      #   predicates:
      #   - Path="'/**'"
      #   filters:
      #   - RewritePath="'/**'", "/ui"
      discovery:
        locator:
          enabled: true
          predicates:
          - Path=/test/**
#           filters:
#           - RewritePath=/test/(?<segment>.*),/test/ahmed
