spring:
  cloud:
    gateway:
      locator:
        enabled: true
        predicates:
          - name: Path
            args:
              pattern: "'test/**'"
#         filters:
#           - name: RewritePath
#             args:
#               regexp: "'test/(?<remaining>.*)'"
#               replacement: "'test/Ahmed'"
