spring:
  cloud:
    gateway:
      discovery:
        locator:
          predicates: 
          - Path="'/'+serviceId+'/test/**'"
          filters:
          - RewritePath="'/'+serviceId+'/test/(?<remaining>.*)'",'/'+"serviceId+'/test/Ahmed'"
