spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: democlient1-service
          uri: lb://democlient1
          predicates:
            - Path=/test/**
          filters:
            - RewritePath=/test/(?<path>.*), /test/Ahmed
